class YZG_Variable {
	private uint id;

	static YZG_Variable internalCreate(uint curId) {
		let ret = new();
		ret.id = curId;
		return ret;
	}

	uint getId() { return self.id; }
}
class YZG_VariableHasher : YZG_Hasher {
	override uint hash(Object o) { return YZG_Variable(o).getId(); }
	override bool eq(Object o0, Object o1) {
		return YZG_Variable(o0).getId() == YZG_Variable(o1).getId();
	}
}

struct YZG_VariableManager {
	private uint curId;

	YZG_Variable createVariable() {
		let ret = YZG_Variable.internalCreate(self.curId);
		self.curId += 1;
		return ret;
	}
}

class YZG_Term {
	YZG_Variable variable;
	double coefficient;

	static YZG_Term create(YZG_Variable variable, double coefficient) {
		let ret = new();
		ret.variable = variable;
		ret.coefficient = coefficient;
		return ret;
	}
}

class YZG_Expr {
	Array<YZG_Term> terms;
	double constant;

	static YZG_Expr fromConstant(double v) {
		let ret = new();
		ret.constant = v;
		return ret;
	}
	static YZG_Expr c(double v) { return YZG_Expr.fromConstant(v); }

	static YZG_Expr fromTerm(YZG_Term term) {
		let ret = new();
		ret.terms.push(term);
		return ret;
	}

	static YZG_Expr fromVariable(YZG_Variable variable) {
		let ret = new();
		ret.terms.push(YZG_Term.create(variable, 1.0));
		return ret;
	}
	static YZG_Expr v(YZG_Variable variable) { return YZG_Expr.fromVariable(variable); }

	static YZG_Expr create() {
		let ret = new();
		return ret;
	}

	void negate() {
		self.constant = -self.constant;
		for (let i = 0; i < self.terms.size(); i++) {
			let t = self.terms[i];
			t.coefficient = -t.coefficient;
		}
	}

	YZG_Expr addAssignVariable(YZG_Variable variable, double coefficient = 1.0) {
		self.terms.push(YZG_Term.create(variable, coefficient));
		return self;
	}
	YZG_Expr addAssignConstant(double constant) {
		self.constant += constant;
		return self;
	}
	YZG_Expr addAssignExpression(YZG_Expr e) {
		for (let i = 0; i < e.terms.size(); i++) {
			self.terms.push(e.terms[i]);
		}
		self.constant += e.constant;
		return self;
	}
	YZG_Expr mulAssign(double coeff) {
		for (let i = 0; i < self.terms.size(); i++) {
			self.terms[i].coefficient *= coeff;
		}
		self.constant *= coeff;
		return self;
	}
}

struct YZG_Strength {
	static double create(double a, double b, double c, double w) {
		return
			clamp(a * w, 0.0, 1000.0) * 1000000.0 +
			clamp(b * w, 0.0, 1000.0) * 1000.0 +
			clamp(c * w, 0.0, 1000.0);
	}

	const REQUIRED = 1001001000.0;
	const STRONG = 1000000.0;
	const MEDIUM = 1000.0;
	const WEAK = 1.0;

	static double clip(double s) {
		return clamp(s, 0.0, REQUIRED);
	}
}

enum YZG_Rel {
	YZG_Rel_LEq,
	YZG_Rel_Eq,
	YZG_Rel_GEq,
}

struct YZG_ConstraintManager {
	private uint curId;

	YZG_Constraint createConstraint(YZG_Expr e, YZG_Rel op, double strength) {
		let ret = YZG_Constraint.internalCreate(e, op, strength, self.curId);
		self.curId += 1;
		return ret;
	}
}

class YZG_Constraint {
	private YZG_Expr expression;
	private double strength;
	private YZG_Rel op;
	private uint id;

	static YZG_Constraint internalCreate(YZG_Expr e, YZG_Rel op, double strength, uint curId) {
		let ret = new();
		ret.expression = e;
		ret.op = op;
		ret.strength = strength;
		ret.id = curId;
		return ret;
	}

	YZG_Expr getExpr() { return self.expression; }
	YZG_Rel getOp() { return self.op; }
	double getStrength() { return self.strength; }
	uint getId() { return self.id; }
}
class YZG_ConstraintHasher : YZG_Hasher {
	override uint hash(Object o) { return YZG_Constraint(o).getId(); }
	override bool eq(Object o0, Object o1) {
		return YZG_Constraint(o0).getId() == YZG_Constraint(o1).getId();
	}
}

class YZG_ConstraintBuilderWithRhs {
	YZG_Expr lhs;
	YZG_Expr rhs;
	YZG_Rel rel;
	double strength;
}

enum YZG_SymbolKind {
	YZG_SymbolKind_Invalid,
	YZG_SymbolKind_External,
	YZG_SymbolKind_Slack,
	YZG_SymbolKind_Error,
	YZG_SymbolKind_Dummy,
}

class YZG_Symbol {
	uint id;
	YZG_SymbolKind kind;

	static YZG_Symbol invalid() {
		let ret = new();
		ret.id = 0;
		ret.kind = YZG_SymbolKind_Invalid;
		return ret;
	}

	static YZG_Symbol create(uint id, YZG_SymbolKind kind) {
		let ret = new();
		ret.id = id;
		ret.kind = kind;
		return ret;
	}

	YZG_Symbol clone() {
		let ret = new();
		ret.id = self.id;
		ret.kind = self.kind;
		return ret;
	}

	String repr() {
		let ret = "Symbol(";
		ret.appendFormat("%d, ", self.id);
		switch (self.kind) {
			case YZG_SymbolKind_Invalid:  ret.appendFormat("Invalid"); break;
			case YZG_SymbolKind_External: ret.appendFormat("External"); break;
			case YZG_SymbolKind_Slack:    ret.appendFormat("Slack"); break;
			case YZG_SymbolKind_Error:    ret.appendFormat("Error"); break;
			case YZG_SymbolKind_Dummy:    ret.appendFormat("Dummy"); break;
		}
		ret.appendFormat(")");
		return ret;
	}
}

class YZG_SymbolHasher : YZG_Hasher {
	override uint hash(Object o) {
		let o = YZG_Symbol(o);
		let seed = o.id;
		hashCombine(seed, o.kind);
		return seed;
	}
	override bool eq(Object o0, Object o1) {
		let o0 = YZG_Symbol(o0);
		let o1 = YZG_Symbol(o1);

		return
			o0.id == o1.id &&
			o0.kind == o1.kind;
	}
}

class YZG_Row {
	YZG_HashMap/*<Symbol, BoxedDouble>*/ cells;
	double constant;

	static YZG_Row create(double constant) {
		let ret = new();
		ret.cells = YZG_HashMap.create(new("YZG_SymbolHasher"));
		ret.constant = constant;
		return ret;
	}

	YZG_Row clone() {
		let ret = new();
		ret.cells = YZG_HashMap.create(new("YZG_SymbolHasher"));
		let iter = self.cells.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let k = YZG_Symbol(ko);
			let v = YZG_BoxedDouble(vo);

			ret.cells.insert(k.clone(), v.clone());
		}
		ret.constant = self.constant;
		return ret;
	}

	double add(double v) {
		self.constant += v;
		return self.constant;
	}

	void insertSymbol(YZG_Symbol s, double coefficient) {
		let g = self.cells.get(s);
		if (g is "YZG_HashUnoccupied") {
			if (!YZG_GlobalMaths.nearZero(coefficient)) {
				self.cells.insert(s, YZG_BoxedDouble.create(coefficient));
			}
		} else {
			let g = YZG_BoxedDouble(g);
			g.val += coefficient;
			if (YZG_GlobalMaths.nearZero(g.val)) {
				self.cells.remove(s);
			}
		}
	}

	bool insertRow(YZG_Row other, double coefficient) {
		let constantDiff = other.constant * coefficient;
		self.constant += constantDiff;
		let iter = other.cells.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let s = YZG_Symbol(ko);
			let v = YZG_BoxedDouble(vo).val;

			self.insertSymbol(s, v * coefficient);
		}
		return constantDiff != 0.0;
	}

	void remove(YZG_Symbol s) {
		self.cells.remove(s);
	}

	void reverseSign() {
		self.constant = -self.constant;
		let iter = self.cells.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }
			let v = YZG_BoxedDouble(vo);
			v.val = -v.val;
		}
	}

	void solveForSymbol(YZG_Symbol s) {
		let e = YZG_BoxedDouble(self.cells.remove(s)).val;
		let coeff = -1.0 / e;
		self.constant *= coeff;
		let iter = self.cells.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }
			let v = YZG_BoxedDouble(vo);
			v.val *= coeff;
		}
	}

	void solveForSymbols(YZG_Symbol lhs, YZG_Symbol rhs) {
		self.insertSymbol(lhs, -1.0);
		self.solveForSymbol(rhs);
	}

	double coefficientFor(YZG_Symbol s) {
		let v = self.cells.get(s);
		return (!(v is "YZG_HashUnoccupied")) ? YZG_BoxedDouble(v).val : 0.0;
	}

	bool substitute(YZG_Symbol s, YZG_Row row) {
		let e = self.cells.remove(s);
		if (!(e is "YZG_HashUnoccupied")) {
			let coeff = YZG_BoxedDouble(e).val;
			return self.insertRow(row, coeff);
		} else {
			return false;
		}
	}
}

enum YZG_AddConstraintError {
	YZG_AddConstraintError_None,
	YZG_AddConstraintError_DuplicateConstraint,
	YZG_AddConstraintError_UnsatisfiableConstraint,
}

enum YZG_RemoveConstraintError {
	YZG_RemoveConstraintError_None,
	YZG_RemoveConstraintError_UnknownConstraint,
}

enum YZG_AddEditVariableError {
	YZG_AddEditVariableError_None,
	YZG_AddEditVariableError_DuplicateEditVariable,
	YZG_AddEditVariableError_BadRequiredStrength,
}

enum YZG_RemoveEditVariableError {
	YZG_RemoveEditVariableError_None,
	YZG_RemoveEditVariableError_UnknownEditVariable,
}

enum YZG_SuggestValueError {
	YZG_SuggestValueError_None,
	YZG_SuggestValueError_UnknownEditVariable,
}

class YZG_Tag {
	YZG_Symbol marker;
	YZG_Symbol other;

	static YZG_Tag create(YZG_Symbol marker = NULL, YZG_Symbol other = NULL) {
		let ret = new();
		ret.marker = marker;
		ret.other = other;
		return ret;
	}
}

class YZG_EditInfo {
	YZG_Tag tag;
	YZG_Constraint constraint;
	double constant;

	static YZG_EditInfo create(YZG_Tag tag, YZG_Constraint constraint, double constant) {
		let ret = new();
		ret.tag = tag;
		ret.constraint = constraint;
		ret.constant = constant;
		return ret;
	}
}

class YZG_VarDataEntry {
	double value;
	YZG_Symbol symbol;
	uint count;

	static YZG_VarDataEntry create(double value, YZG_Symbol symbol, uint count) {
		let ret = new();
		ret.value = value;
		ret.symbol = symbol;
		ret.count = count;
		return ret;
	}
}

class YZG_PublicChangesEntry {
	YZG_Variable variable;
	double value;

	static YZG_PublicChangesEntry create(YZG_Variable variable, double value) {
		let ret = new();
		ret.variable = variable;
		ret.value = value;
		return ret;
	}
}

class YZG_Solver {
	private YZG_HashMap/*<Constraint, Tag>*/ cns;
	private YZG_HashMap/*<Variable, VarDataEntry>*/ varData;
	private YZG_HashMap/*<Symbol, Variable>*/ varForSymbol;
	private Array<YZG_PublicChangesEntry> publicChanges;
	private YZG_HashSet/*<Variable>*/ changed;
	private bool shouldClearChanges;
	private YZG_HashMap/*<Symbol, Row>*/ rows;
	private YZG_HashMap/*<Variable, EditInfo>*/ edits;
	private Array<YZG_Symbol> infeasibleRows;
	private YZG_Row objective;
	private /* Nullable */ YZG_Row artificial;
	private uint idTick;

	private YZG_VariableManager variableManager;
	YZG_ConstraintManager constraintManager;

	static YZG_Solver create() {
		let constraintHasher = new("YZG_ConstraintHasher");
		let variableHasher = new("YZG_VariableHasher");
		let symbolHasher = new("YZG_SymbolHasher");

		let ret = new();
		ret.cns = YZG_HashMap.create(constraintHasher);
		ret.varData = YZG_HashMap.create(variableHasher);
		ret.varForSymbol = YZG_HashMap.create(symbolHasher);
		/* ret.publicChanges = default; */
		ret.changed = YZG_HashSet.create(variableHasher);
		ret.shouldClearChanges = false;
		ret.rows = YZG_HashMap.create(symbolHasher);
		ret.edits = YZG_HashMap.create(variableHasher);
		/* ret.infeasibleRows = default; */
		ret.objective = YZG_Row.create(0.0);
		ret.artificial = NULL;
		ret.idTick = 1;

		return ret;
	}

	YZG_Variable createVariable() {
		return self.variableManager.createVariable();
	}

	static void assertNoErr(int errcode) {
		if (errcode != 0) { throwAbortException("err %d", errcode); }
	}

	YZG_AddConstraintError, YZG_Constraint addConstraintFromRelation(
		YZG_Expr lhs,
		Name op,
		YZG_Expr rhs,
		double strength = YZG_Strength.REQUIRED
	) {
		rhs.negate();
		lhs.addAssignExpression(rhs);
		if (op != '==' && op != '<=' && op != '>=') {
			throwAbortException("invalid op string '%s'", op);
		}
		let op = (op == '==') ? YZG_Rel_Eq : (op == '<=') ? YZG_Rel_Leq : YZG_Rel_Geq;
		let constraint = self.constraintManager.createConstraint(lhs, op, strength);
		return self.addConstraint(constraint), constraint;
	}

	YZG_AddConstraintError addConstraint(YZG_Constraint constraint) {
		if (self.cns.containsKey(constraint)) {
			return YZG_AddConstraintError_DuplicateConstraint;
		}

		YZG_Row row; YZG_Tag tag;
		[row, tag] = self.createRow(constraint);
		let subject = chooseSubject(row, tag);

		if (subject.kind == YZG_SymbolKind_Invalid && allDummies(row)) {
			if (!YZG_GlobalMaths.nearZero(row.constant)) {
				return YZG_AddConstraintError_UnsatisfiableConstraint;
			} else {
				subject = tag.marker;
			}
		}
		if (subject.kind == YZG_SymbolKind_Invalid) {
			if (!self.addWithArtificialVariable(row)) {
				return YZG_AddConstraintError_UnsatisfiableConstraint;
			}
		} else {
			row.solveForSymbol(subject);
			self.substitute(subject, row);

			if (subject.kind == YZG_SymbolKind_External && row.constant != 0.0) {
				let v = YZG_Variable(self.varForSymbol.get(subject));
				self.varChanged(v);
			}
			self.rows.insert(subject, row);
		}

		self.cns.insert(constraint, tag);

		let objective = self.objective;
		self.optimise(objective);

		return YZG_AddConstraintError_None;
	}

	YZG_RemoveConstraintError removeConstraint(YZG_Constraint constraint) {
		let t = self.cns.remove(constraint);
		if (t is "YZG_HashUnoccupied") {
			return YZG_RemoveConstraintError_UnknownConstraint;
		}
		let tag = YZG_Tag(t);

		self.removeConstraintEffects(constraint, tag);

		if (self.rows.remove(tag.marker) is "YZG_HashUnoccupied") {
			YZG_Symbol leaving; YZG_Row row;
			[leaving, row] = self.getMarkerLeavingRow(tag.marker);
			row.solveForSymbols(leaving, tag.marker);
			self.substitute(tag.marker, row);
		}

		let objective = self.objective;
		self.optimise(objective);

		let cexpr = constraint.getExpr();
		for (let i = 0; i < cexpr.terms.size(); i++) {
			let term = cexpr.terms[i];
			if (!YZG_GlobalMaths.nearZero(term.coefficient)) {
				let shouldRemove = false;
				let v = self.varData.get(term.variable);
				if (!(v is "YZG_HashUnoccupied")) {
					let v = YZG_VarDataEntry(v);
					v.count -= 1;
					shouldRemove = v.count == 0;
				}
				if (shouldRemove) {
					self.varForSymbol.remove(YZG_VarDataEntry(self.varData.get(term.variable)).symbol);
					self.varData.remove(term.variable);
				}
			}
		}

		return YZG_RemoveConstraintError_None;
	}

	bool hasConstraint(YZG_Constraint constraint) {
		return self.cns.containsKey(constraint);
	}

	YZG_AddEditVariableError addEditVariable(YZG_Variable v, double strength) {
		if (self.edits.containsKey(v)) {
			return YZG_AddEditVariableError_DuplicateEditVariable;
		}
		let strength = YZG_Strength.clip(strength);
		if (strength == YZG_Strength.REQUIRED) {
			return YZG_AddEditVariableError_BadRequiredStrength;
		}
		let cn = self.constraintManager.createConstraint(
			YZG_Expr.fromTerm(YZG_Term.create(v, 1.0)),
			YZG_Rel_Eq,
			strength
		);
		{
			let err = self.addConstraint(cn);
			if (err != 0) { throwAbortException("shouldn't happen"); }
		}
		self.edits.insert(
			v,
			YZG_EditInfo.create(
				YZG_Tag(self.cns.get(cn)),
				cn,
				0.0
			)
		);

		return YZG_AddEditVariableError_None;
	}

	YZG_RemoveEditVariableError removeEditVariable(YZG_Variable v) {
		let e = self.edits.remove(v);
		if (!(e is "YZG_HashUnoccupied")) {
			let constraint = YZG_EditInfo(e).constraint;
			let err = self.removeConstraint(constraint);
			if (err == YZG_RemoveConstraintError_UnknownConstraint) {
				throwAbortException("Edit constraint not in system.");
			}
			return YZG_RemoveEditVariableError_None;
		} else {
			return YZG_RemoveEditVariableError_UnknownEditVariable;
		}
	}

	bool hasEditVariable(YZG_Variable v) {
		return self.edits.containsKey(v);
	}

	YZG_SuggestValueError suggestValue(YZG_Variable variable, double value) {
		let i = self.edits.get(variable);
		if (i is "YZG_HashUnoccupied") {
			return YZG_SuggestValueError_UnknownEditVariable;
		}
		let info = YZG_EditInfo(i);
		let infoTagMarker = info.tag.marker;
		let infoTagOther = info.tag.other;
		let delta = value - info.constant;
		info.constant = value;

		{
			let rm = self.rows.get(infoTagMarker);
			let ro = self.rows.get(infoTagOther);
			if (!(rm is "YZG_HashUnoccupied")) {
				let row = YZG_Row(rm);
				if (row.add(-delta) < 0.0) {
					infeasibleRows.push(infoTagMarker);
				}
			} else if (!(ro is "YZG_HashUnoccupied")) {
				let row = YZG_Row(ro);
				if (row.add(delta) < 0.0) {
					infeasibleRows.push(infoTagOther);
				}
			} else {
				let iter = self.rows.iter();
				while (true) {
					Object ko, vo;
					[ko, vo] = iter.next();
					if (ko is "YZG_HashUnoccupied") { break; }

					let symbol = YZG_Symbol(ko);
					let row = YZG_Row(vo);

					let coeff = row.coefficientFor(infoTagMarker);
					let diff = delta * coeff;
					if (diff != 0.0 && symbol.kind == YZG_SymbolKind_External) {
						let v = YZG_Variable(self.varForSymbol.get(symbol));
						if (self.shouldClearChanges) {
							self.changed.clear();
							self.shouldClearChanges = false;
						}
						self.changed.insert(v);
					}
					if (
						coeff != 0.0 &&
						row.add(diff) < 0.0 &&
						symbol.kind != YZG_SymbolKind_External
					) {
						infeasibleRows.push(symbol);
					}
				}
			}
		}

		self.dualOptimise();

		return YZG_SuggestValueError_None;
	}

	private void varChanged(YZG_Variable v) {
		if (self.shouldClearChanges) {
			self.changed.clear();
			self.shouldClearChanges = false;
		}
		self.changed.insert(v);
	}

	void fetchChanges(out Array<YZG_PublicChangesEntry> ret) {
		if (self.shouldClearChanges) {
			self.changed.clear();
			self.shouldClearChanges = false;
		} else {
			self.shouldClearChanges = true;
		}
		self.publicChanges.clear();

		let iter = self.changed.iter();
		while (true) {
			let vo = iter.next();
			if (vo is "YZG_HashUnoccupied") { break; }
			let v = YZG_Variable(vo);

			let vd = self.varData.get(v);
			if (!(vd is "YZG_HashUnoccupied")) {
				let varData = YZG_VarDataEntry(vd);
				let r = self.rows.get(varData.symbol);
				let newValue = 0.0;
				if (!(r is "YZG_HashUnoccupied")) {
					newValue = YZG_Row(r).constant;
				}
				let oldValue = varData.value;
				if (oldValue != newValue) {
					self.publicChanges.push(
						YZG_PublicChangesEntry.create(v, newValue)
					);
					varData.value = newValue;
				}
			}
		}

		ret.copy(self.publicChanges);
	}

	void reset() {
		self.rows.clear();
		self.cns.clear();
		self.varData.clear();
		self.varForSymbol.clear();
		self.changed.clear();
		self.shouldClearChanges = false;
		self.edits.clear();
		self.infeasibleRows.clear();
		self.objective = YZG_Row.create(0.0);
		self.artificial = NULL;
		self.idTick = 1;
	}

	private YZG_Symbol getVarSymbol(YZG_Variable v) {
		YZG_VarDataEntry value;
		let vd = self.varData.get(v);
		if (!(vd is "YZG_HashUnoccupied")) {
			value = YZG_VarDataEntry(vd);
		} else {
			let s = YZG_Symbol.create(self.idTick, YZG_SymbolKind_External);
			self.varForSymbol.insert(s, v);
			self.idTick += 1;
			value = YZG_VarDataEntry.create(double.NAN, s, 0);
			self.varData.insert(v, value);
		}
		value.count += 1;
		return value.symbol;
	}

	private YZG_Row, YZG_Tag createRow(YZG_Constraint constraint) {
		let expr = constraint.getExpr();
		let row = YZG_Row.create(expr.constant);
		for (let i = 0; i < expr.terms.size(); i++) {
			let term = expr.terms[i];
			if (!YZG_GlobalMaths.nearZero(term.coefficient)) {
				let symbol = self.getVarSymbol(term.variable);
				let o = self.rows.get(symbol);
				if (!(o is "YZG_HashUnoccupied")) {
					let otherRow = YZG_Row(o);
					row.insertRow(otherRow, term.coefficient);
				} else {
					row.insertSymbol(symbol, term.coefficient);
				}
			}
		}

		let objective = self.objective;

		YZG_Tag tag;
		let constraintOp = constraint.getOp();
		switch (constraintOp) {
		case YZG_Rel_Geq:
		case YZG_Rel_Leq: {
			let coeff = (constraintOp == YZG_Rel_Leq) ? 1.0 : -1.0;
			let slack = YZG_Symbol.create(self.idTick, YZG_SymbolKind_Slack);
			self.idTick += 1;
			row.insertSymbol(slack, coeff);
			let constraintStrength = constraint.getStrength();
			if (constraintStrength < YZG_Strength.REQUIRED) {
				let error = YZG_Symbol.create(self.idTick, YZG_SymbolKind_Error);
				self.idTick += 1;
				row.insertSymbol(error, -coeff);
				objective.insertSymbol(error, constraintStrength);
				tag = YZG_Tag.create(
					marker: slack,
					other: error
				);
			} else {
				tag = YZG_Tag.create(
					marker: slack,
					other: YZG_Symbol.invalid()
				);
			}
			break;
		}
		case YZG_Rel_Eq: {
			let constraintStrength = constraint.getStrength();
			if (constraintStrength < YZG_Strength.REQUIRED) {
				let errplus = YZG_Symbol.create(self.idTick, YZG_SymbolKind_Error);
				self.idTick += 1;
				let errminus = YZG_Symbol.create(self.idTick, YZG_SymbolKind_Error);
				self.idTick += 1;
				row.insertSymbol(errplus,  -1.0);
				row.insertSymbol(errminus,  1.0);
				objective.insertSymbol(errplus, constraintStrength);
				objective.insertSymbol(errminus, constraintStrength);
				tag = YZG_Tag.create(
					marker: errplus,
					other: errminus
				);
			} else {
				let dummy = YZG_Symbol.create(self.idTick, YZG_SymbolKind_Dummy);
				self.idTick += 1;
				row.insertSymbol(dummy, 1.0);
				tag = YZG_Tag.create(
					marker: dummy,
					other: YZG_Symbol.invalid()
				);
			}
			break;
		}
		default:
			throwAbortException("shouldn't happen");
		}

		if (row.constant < 0.0) {
			row.reverseSign();
		}
		return row, tag;
	}

	static private YZG_Symbol chooseSubject(YZG_Row row, YZG_Tag tag) {
		let iter = row.cells.iter();
		while (true) {
			let ko = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }
			let s = YZG_Symbol(ko);

			if (s.kind == YZG_SymbolKind_External) {
				return s;
			}
		}
		if (tag.marker.kind == YZG_SymbolKind_Slack || tag.marker.kind == YZG_SymbolKind_Error) {
			if (row.coefficientFor(tag.marker) < 0.0) {
				return tag.marker;
			}
		}
		if (tag.other.kind == YZG_SymbolKind_Slack || tag.other.kind == YZG_SymbolKind_Error) {
			if (row.coefficientFor(tag.other) < 0.0) {
				return tag.other;
			}
		}
		return YZG_Symbol.invalid();
	}

	private bool addWithArtificialVariable(YZG_Row row) {
		let art = YZG_Symbol.create(self.idTick, YZG_SymbolKind_Slack);
		self.idTick += 1;
		self.rows.insert(art, row.clone());
		self.artificial = row.clone();

		let artificial = self.artificial;
		self.optimise(artificial);
		let success = YZG_GlobalMaths.nearZero(artificial.constant);
		self.artificial = NULL;

		let r = self.rows.remove(art);
		if (!(r is "YZG_HashUnoccupied")) {
			let row = YZG_Row(r);
			if (row.cells.isEmpty()) {
				return success;
			}
			let entering = anyPivotableSymbol(row);
			if (entering.kind == YZG_SymbolKind_Invalid) {
				return false;
			}
			row.solveForSymbols(art, entering);
			self.substitute(entering, row);
			self.rows.insert(entering, row);
		}

		let iter = self.rows.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let row = YZG_Row(vo);

			row.remove(art);
		}
		self.objective.remove(art);
		return success;
	}

	private void substitute(YZG_Symbol symbol, YZG_Row row) {
		let iter = self.rows.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let otherSymbol = YZG_Symbol(ko);
			let otherRow = YZG_Row(vo);

			let constantChanged = otherRow.substitute(symbol, row);
			if (otherSymbol.kind == YZG_SymbolKind_External && constantChanged) {
				let v = YZG_Variable(self.varForSymbol.get(otherSymbol));
				if (self.shouldClearChanges) {
					self.changed.clear();
					self.shouldClearChanges = false;
				}
				self.changed.insert(v);
			}
			if (otherSymbol.kind != YZG_SymbolKind_External && otherRow.constant < 0.0) {
				self.infeasibleRows.push(otherSymbol);
			}
		}
		self.objective.substitute(symbol, row);
		if (self.artificial != NULL) {
			let artificial = self.artificial;
			artificial.substitute(symbol, row);
		}
	}

	private void optimise(YZG_Row objective) {
		while (true) {
			let entering = getEnteringSymbol(objective);
			if (entering.kind == YZG_SymbolKind_Invalid) {
				return;
			}
			YZG_Symbol leaving;
			YZG_Row row;
			[leaving, row] = self.getLeavingRow(entering);
			if (leaving == NULL) {
				throwAbortException("internal solver error: the objective is unbounded");
			}
			row.solveForSymbols(leaving, entering);
			self.substitute(entering, row);
			if (entering.kind == YZG_SymbolKind_External && row.constant != 0.0) {
				let v = YZG_Variable(self.varForSymbol.get(entering));
				self.varChanged(v);
			}
			self.rows.insert(entering, row);
		}
	}

	private void dualOptimise() {
		while (self.infeasibleRows.size() != 0u) {
			let leaving = self.infeasibleRows[self.infeasibleRows.size() - 1];
			self.infeasibleRows.pop();

			YZG_Row row;
			let e = self.rows.get(leaving);
			if (!(e is "YZG_HashUnoccupied")) {
				let entry = YZG_Row(e);
				if (entry.constant < 0.0) {
					row = entry;
					self.rows.remove(leaving);
				} else {
					row = NULL;
				}
			} else {
				row = NULL;
			}
			if (row != NULL) {
				let entering = self.getDualEnteringSymbol(row);
				if (entering.kind == YZG_SymbolKind_Invalid) {
					throwAbortException("internal solver error: dual optimise failed");
				}
				row.solveForSymbols(leaving, entering);
				self.substitute(entering, row);
				if (entering.kind == YZG_SymbolKind_External && row.constant != 0.0) {
					let v = YZG_Variable(self.varForSymbol.get(entering));
					self.varChanged(v);
				}
				self.rows.insert(entering, row);
			}
		}
	}

	private YZG_Symbol getEnteringSymbol(YZG_Row objective) {
		let iter = objective.cells.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let symbol = YZG_Symbol(ko);
			let value = YZG_BoxedDouble(vo).val;

			if (symbol.kind != YZG_SymbolKind_Dummy && value < 0.0) {
				return symbol;
			}
		}
		return YZG_Symbol.invalid();
	}

	private YZG_Symbol getDualEnteringSymbol(YZG_Row row) {
		let entering = YZG_Symbol.invalid();
		let ratio = double.INFINITY;
		let objective = self.objective;
		let iter = row.cells.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let symbol = YZG_Symbol(ko);
			let value = YZG_BoxedDouble(vo).val;

			if (value > 0.0 && symbol.kind != YZG_SymbolKind_Dummy) {
				let coeff = objective.coefficientFor(symbol);
				let r = coeff / value;
				if (r < ratio) {
					ratio = r;
					entering = symbol;
				}
			}
		}
		return entering;
	}

	private static YZG_Symbol anyPivotableSymbol(YZG_Row row) {
		let iter = row.cells.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let symbol = YZG_Symbol(ko);

			if (symbol.kind == YZG_SymbolKind_Slack || symbol.kind == YZG_SymbolKind_Error) {
				return symbol;
			}
		}
		return YZG_Symbol.invalid();
	}

	private YZG_Symbol, YZG_Row getLeavingRow(YZG_Symbol entering) {
		let ratio = double.INFINITY;
		YZG_Symbol found = NULL;
		let iter = self.rows.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let symbol = YZG_Symbol(ko);
			let row = YZG_Row(vo);

			if (symbol.kind != YZG_SymbolKind_External) {
				let temp = row.coefficientFor(entering);
				if (temp < 0.0) {
					let tempRatio = -row.constant / temp;
					if (tempRatio < ratio) {
						ratio = tempRatio;
						found = symbol;
					}
				}
			}
		}
		if (found != NULL) {
			return found, YZG_Row(self.rows.remove(found));
		} else {
			return NULL, NULL;
		}
	}

	private YZG_Symbol, YZG_Row getMarkerLeavingRow(YZG_Symbol marker) {
		let r1 = double.INFINITY;
		let r2 = r1;
		YZG_Symbol first = NULL;
		YZG_Symbol second = NULL;
		YZG_Symbol third = NULL;
		let iter = self.rows.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let symbol = YZG_Symbol(ko);
			let row = YZG_Row(vo);

			let c = row.coefficientFor(marker);
			if (c == 0.0) {
				continue;
			}
			if (symbol.kind == YZG_SymbolKind_External) {
				third = symbol;
			} else if (c < 0.0) {
				let r = -row.constant / c;
				if (r < r1) {
					r1 = r;
					first = symbol;
				}
			} else {
				let r = row.constant / c;
				if (r < r2) {
					r2 = r;
					second = symbol;
				}
			}
		}
		let s =
			(first != NULL)
			? first
			: (second != NULL)
			  ? second
			  : third;
		if (s != NULL) {
			if (s.kind == YZG_SymbolKind_External && YZG_Row(self.rows.get(s)).constant != 0.0) {
				let v = YZG_Variable(self.varForSymbol.get(s));
				self.varChanged(v);
			}
			let r = self.rows.remove(s);
			if (!(r is "YZG_HashUnoccupied")) {
				return s, YZG_Row(r);
			} else {
				return NULL, NULL;
			}
		} else {
			return NULL, NULL;
		}
	}

	private void removeConstraintEffects(YZG_Constraint cn, YZG_Tag tag) {
		if (tag.marker.kind == YZG_SymbolKind_Error) {
			self.removeMarkerEffects(tag.marker, cn.getStrength());
		} else if (tag.other.kind == YZG_SymbolKind_Error) {
			self.removeMarkerEffects(tag.other, cn.getStrength());
		}
	}

	private void removeMarkerEffects(YZG_Symbol marker, double strength) {
		let r = self.rows.get(marker);
		if (!(r is "YZG_HashUnoccupied")) {
			let row = YZG_Row(r);
			self.objective.insertRow(row, -strength);
		} else {
			self.objective.insertSymbol(marker, -strength);
		}
	}

	private static bool allDummies(YZG_Row row) {
		let iter = row.cells.iter();
		while (true) {
			let ko = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }
			let s = YZG_Symbol(ko);

			if (s.kind != YZG_SymbolKind_Dummy) {
				return false;
			}
		}
		return true;
	}

	static void printRow(YZG_Row row) {
		let ret = "row = Row {\n    cells: {\n";

		let iter = row.cells.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let symbol = YZG_Symbol(ko);
			let val = YZG_BoxedDouble(vo).val;

			ret.appendFormat("        %s: %f,\n", symbol.repr(), val);
		}
		ret.appendFormat("    },\n    constant: %f,\n}", row.constant);
		Console.printf(ret);
	}

	private void printRows() {
		let ret = "self.rows = {\n";
		let iter = self.rows.iter();
		while (true) {
			Object ko, vo;
			[ko, vo] = iter.next();
			if (ko is "YZG_HashUnoccupied") { break; }

			let symbol = YZG_Symbol(ko);
			let row = YZG_Row(vo);

			ret.appendFormat("    %s: Row {\n        cells: {\n", symbol.repr());

			let iter = row.cells.iter();
			while (true) {
				Object ko, vo;
				[ko, vo] = iter.next();
				if (ko is "YZG_HashUnoccupied") { break; }

				let symbol = YZG_Symbol(ko);
				let val = YZG_BoxedDouble(vo).val;

				ret.appendFormat("            %s: %f,\n", symbol.repr(), val);
			}
			ret.appendFormat("        },\n        constant: %f,\n    },\n", row.constant);
		}
		ret.appendFormat("}");
		Console.printf(ret);
	}
}
