class yzHasher abstract {
	abstract virtualscope uint hash(Object o);
	abstract virtualscope bool eq(Object o0, Object o1);
	static void hashCombine(out uint seed, uint other) {
		seed ^= other + 0x9E3779B9 + (seed << 6) + (seed >> 2);
	}
}

class yzBoxedInt {
	int val;
	static yzBoxedInt create(int val) {
		let ret = new();
		ret.val = val;
		return ret;
	}
	yzBoxedInt clone() {
		let ret = new();
		ret.val = self.val;
		return ret;
	}
}
class yzIntHasher : yzHasher {
	override uint hash(Object o) { return yzBoxedInt(o).val; }
	override bool eq(Object o0, Object o1) { return yzBoxedInt(o0).val == yzBoxedInt(o1).val; }
}

class yzBoxedUInt {
	uint val;
	static yzBoxedUInt create(uint val) {
		let ret = new();
		ret.val = val;
		return ret;
	}
	yzBoxedUInt clone() {
		let ret = new();
		ret.val = self.val;
		return ret;
	}
}
class yzUIntHasher : yzHasher {
	override uint hash(Object o) { return yzBoxedUInt(o).val; }
	override bool eq(Object o0, Object o1) { return yzBoxedUInt(o0).val == yzBoxedUInt(o1).val; }
}

class yzBoxedDouble {
	double val;
	static yzBoxedDouble create(double val) {
		let ret = new();
		ret.val = val;
		return ret;
	}
	yzBoxedDouble clone() {
		let ret = new();
		ret.val = self.val;
		return ret;
	}
}

class yzBoxedString {
	String val;
	static yzBoxedString create(String val) {
		let ret = new();
		ret.val = val;
		return ret;
	}
	yzBoxedString clone() {
		let ret = new();
		ret.val = self.val;
		return ret;
	}
}

class yzHashSentinel {}

class yzHashUnoccupied {}

class yzKVStorage {
	Array<Object> keys;
	Array<Object> values;
	uint loadCount;

	yzHashUnoccupied unoccupied;

	yzHashSentinel empty;
	yzHashSentinel tombstone;

	const SEED32 = 0x27220a95u;
	private static uint hash(Object key, yzHasher hasher) {
		let h = hasher.hash(key);
		return h * SEED32;
	}

	Object get(Object key, yzHasher hasher) {
		let hash = hash(key, hasher);
		let size = uint(self.keys.size());
		let index = hash % size;
		let i = index;
		while (true) {
			let kb = self.keys[i];
			if (kb == self.empty) {
				break;
			}
			if (kb != self.tombstone && hasher.eq(kb, key)) {
				return self.values[i];
			}
			i = (i + 1) % size;
		}
		return self.unoccupied;
	}

	yzKVStorage resized(uint newSize, yzHasher hasher) {
		let newKV = new("yzKVStorage");
		newKV.keys.resize(newSize);
		newKV.values.resize(newSize);

		newKV.unoccupied = self.unoccupied;
		newKV.empty = self.empty;
		newKV.tombstone = self.tombstone;

		newKV.clear();

		for (let i = 0; i < self.keys.size(); i++) {
			let k = self.keys[i];
			if (k != self.empty && k != self.tombstone) {
				newKV.insert(k, self.values[i], hasher);
			}
		}

		return newKV;
	}

	void insert(Object key, Object value, yzHasher hasher) {
		let hash = hash(key, hasher);
		let size = uint(self.keys.size());
		let index = hash % size;
		{
			let i = index;
			while (true) {
				let kb = self.keys[i];
				if (kb == self.empty) {
					break;
				}
				if (kb != self.tombstone && hasher.eq(kb, key)) {
					self.values[i] = value;
					return;
				}
				i = (i + 1) % size;
			}
		}
		{
			let i = index;
			while (true) {
				let kb = self.keys[i];
				if (kb == self.empty || kb == self.tombstone) {
					self.keys[i] = key;
					self.values[i] = value;
					if (kb == self.empty) {
						self.loadCount += 1;
					}
					break;
				}
				i = (i + 1) % size;
			}
		}
	}

	Object remove(Object key, yzHasher hasher) {
		let hash = hash(key, hasher);
		let size = uint(self.keys.size());
		{
			let index = hash % size;
			let i = index;
			while (true) {
				let kb = self.keys[i];
				if (kb == self.empty) {
					break;
				}
				if (kb != self.tombstone && hasher.eq(kb, key)) {
					let val = self.values[i];
					self.keys[i] = self.tombstone;
					self.values[i] = NULL;
					return val;
				}
				i = (i + 1) % size;
			}
		}
		return self.unoccupied;
	}

	bool isEmpty() {
		for (let i = 0; i < self.keys.size(); i++) {
			let k = self.keys[i];
			if (k != self.empty && k != self.tombstone) {
				return false;
			}
		}
		return true;
	}

	void clear() {
		for (let i = 0; i < self.keys.size(); i++) {
			self.keys[i] = self.empty;
			self.values[i] = NULL;
		}
		self.loadCount = 0u;
	}
}

class yzHashMapIterator {
	private yzKVStorage m;
	private int i;

	static yzHashMapIterator internalCreate(yzKVStorage kv) {
		let ret = new();
		ret.m = kv;
		ret.i = 0;
		return ret;
	}

	Object, Object next() {
		while (self.i < m.keys.size()) {
			let k = m.keys[self.i];
			let v = m.values[self.i];
			self.i += 1;
			if (k != self.m.empty && k != self.m.tombstone) {
				return k, v;
			}
		}
		return self.m.unoccupied, NULL;
	}
}

class yzHashMap {
	private yzKVStorage kv;
	private yzHasher hasher;

	static yzHashMap create(yzHasher hasher) {
		let ret = new();
		ret.kv = new("yzKVStorage");
		ret.kv.keys.resize(8);
		ret.kv.values.resize(8);
		ret.kv.unoccupied = new("yzHashUnoccupied");
		ret.kv.empty = new("yzHashSentinel");
		ret.kv.tombstone = new("yzHashSentinel");
		ret.kv.clear();
		ret.hasher = hasher;
		return ret;
	}

	Object get(Object key) {
		return self.kv.get(key, self.hasher);
	}

	bool containsKey(Object key) {
		return !(self.kv.get(key, self.hasher) is "yzHashUnoccupied");
	}

	void resize(uint newSize) {
		self.kv = self.kv.resized(newSize, hasher);
	}

	void insert(Object key, Object value) {
		if (self.kv.loadCount + 1 > uint(self.kv.keys.size() * 0.5)) {
			self.resize(self.kv.keys.size() * 2);
		}
		self.kv.insert(key, value, self.hasher);
	}

	Object remove(Object key) {
		return self.kv.remove(key, self.hasher);
	}

	bool isEmpty() {
		return self.kv.isEmpty();
	}

	void clear() {
		self.kv.clear();
	}

	yzHashMapIterator iter() {
		return yzHashMapIterator.internalCreate(self.kv);
	}

	String debugRepr() {
		let ret = "";
		for (let i = 0; i < self.kv.keys.size(); i++) {
			ret.appendFormat("%d : ", i);
			let k = self.kv.keys[i];
			if (k == self.kv.empty) {
				ret.appendFormat("EMPTY");
			} else if (k == self.kv.tombstone) {
				ret.appendFormat("TOMBSTONE");
			} else {
				ret.appendFormat("%p -> %p", k, self.kv.values[i]);
			}
			if (i != self.kv.keys.size() - 1) {
				ret.appendFormat("\n");
			}
		}
		return ret;
	}

	double loadFactor() {
		return double(self.kv.loadCount) / double(self.kv.values.size());
	}
	uint bucketCount() {
		return self.kv.values.size();
	}
}

class yzHashSetIterator {
	private yzHashMapIterator i;

	static yzHashSetIterator internalCreate(yzHashMapIterator i) {
		let ret = new();
		ret.i = i;
		return ret;
	}

	Object next() {
		return self.i.next();
	}
}

class yzHashSet {
	private yzHashMap hm;

	static yzHashSet create(yzHasher hasher) {
		let ret = new();
		ret.hm = yzHashMap.create(hasher);
		return ret;
	}

	bool contains(Object key) {
		return self.hm.containsKey(key);
	}

	void resize(uint newSize) {
		self.hm.resize(newSize);
	}

	void insert(Object key) {
		self.hm.insert(key, NULL);
	}

	Object remove(Object key) {
		return self.hm.remove(key);
	}

	bool isEmpty() {
		return self.hm.isEmpty();
	}

	void clear() {
		self.hm.clear();
	}

	yzHashSetIterator iter() {
		return yzHashSetIterator.internalCreate(self.hm.iter());
	}

	String debugRepr() {
		return self.hm.debugRepr();
	}
}
