class YZG_Hasher abstract {
	abstract virtualscope uint hash(Object o);
	abstract virtualscope bool eq(Object o0, Object o1);
	static void hashCombine(out uint seed, uint other) {
		seed ^= other + 0x9E3779B9 + (seed << 6) + (seed >> 2);
	}
}

class YZG_BoxedInt {
	int val;
	static YZG_BoxedInt create(int val) {
		let ret = new();
		ret.val = val;
		return ret;
	}
	YZG_BoxedInt clone() {
		let ret = new();
		ret.val = self.val;
		return ret;
	}
}
class YZG_IntHasher : YZG_Hasher {
	override uint hash(Object o) { return YZG_BoxedInt(o).val; }
	override bool eq(Object o0, Object o1) { return YZG_BoxedInt(o0).val == YZG_BoxedInt(o1).val; }
}

class YZG_BoxedUInt {
	uint val;
	static YZG_BoxedUInt create(uint val) {
		let ret = new();
		ret.val = val;
		return ret;
	}
	YZG_BoxedUInt clone() {
		let ret = new();
		ret.val = self.val;
		return ret;
	}
}
class YZG_UIntHasher : YZG_Hasher {
	override uint hash(Object o) { return YZG_BoxedUInt(o).val; }
	override bool eq(Object o0, Object o1) { return YZG_BoxedUInt(o0).val == YZG_BoxedUInt(o1).val; }
}

class YZG_BoxedDouble {
	double val;
	static YZG_BoxedDouble create(double val) {
		let ret = new();
		ret.val = val;
		return ret;
	}
	YZG_BoxedDouble clone() {
		let ret = new();
		ret.val = self.val;
		return ret;
	}
}

class YZG_BoxedString {
	String val;
	static YZG_BoxedString create(String val) {
		let ret = new();
		ret.val = val;
		return ret;
	}
	YZG_BoxedString clone() {
		let ret = new();
		ret.val = self.val;
		return ret;
	}
}

class YZG_HashSentinel {}

class YZG_HashUnoccupied {}

class YZG_KVStorage {
	Array<Object> keys;
	Array<Object> values;
	uint loadCount;

	YZG_HashUnoccupied unoccupied;

	YZG_HashSentinel empty;
	YZG_HashSentinel tombstone;

	const SEED32 = 0x27220a95u;
	private static uint hash(Object key, YZG_Hasher hasher) {
		let h = hasher.hash(key);
		return h * SEED32;
	}

	Object get(Object key, YZG_Hasher hasher) {
		let hash = hash(key, hasher);
		let size = uint(self.keys.size());
		let index = hash % size;
		let i = index;
		while (true) {
			let kb = self.keys[i];
			if (kb == self.empty) {
				break;
			}
			if (kb != self.tombstone && hasher.eq(kb, key)) {
				return self.values[i];
			}
			i = (i + 1) % size;
		}
		return self.unoccupied;
	}

	YZG_KVStorage resized(uint newSize, YZG_Hasher hasher) {
		let newKV = new("YZG_KVStorage");
		newKV.keys.resize(newSize);
		newKV.values.resize(newSize);

		newKV.unoccupied = self.unoccupied;
		newKV.empty = self.empty;
		newKV.tombstone = self.tombstone;

		newKV.clear();

		for (let i = 0; i < self.keys.size(); i++) {
			let k = self.keys[i];
			if (k != self.empty && k != self.tombstone) {
				newKV.insert(k, self.values[i], hasher);
			}
		}

		return newKV;
	}

	void insert(Object key, Object value, YZG_Hasher hasher) {
		let hash = hash(key, hasher);
		let size = uint(self.keys.size());
		let index = hash % size;
		{
			let i = index;
			while (true) {
				let kb = self.keys[i];
				if (kb == self.empty) {
					break;
				}
				if (kb != self.tombstone && hasher.eq(kb, key)) {
					self.values[i] = value;
					return;
				}
				i = (i + 1) % size;
			}
		}
		{
			let i = index;
			while (true) {
				let kb = self.keys[i];
				if (kb == self.empty || kb == self.tombstone) {
					self.keys[i] = key;
					self.values[i] = value;
					if (kb == self.empty) {
						self.loadCount += 1;
					}
					break;
				}
				i = (i + 1) % size;
			}
		}
	}

	Object remove(Object key, YZG_Hasher hasher) {
		let hash = hash(key, hasher);
		let size = uint(self.keys.size());
		{
			let index = hash % size;
			let i = index;
			while (true) {
				let kb = self.keys[i];
				if (kb == self.empty) {
					break;
				}
				if (kb != self.tombstone && hasher.eq(kb, key)) {
					let val = self.values[i];
					self.keys[i] = self.tombstone;
					self.values[i] = NULL;
					return val;
				}
				i = (i + 1) % size;
			}
		}
		return self.unoccupied;
	}

	bool isEmpty() {
		for (let i = 0; i < self.keys.size(); i++) {
			let k = self.keys[i];
			if (k != self.empty && k != self.tombstone) {
				return false;
			}
		}
		return true;
	}

	void clear() {
		for (let i = 0; i < self.keys.size(); i++) {
			self.keys[i] = self.empty;
			self.values[i] = NULL;
		}
		self.loadCount = 0u;
	}
}

class YZG_HashMapIterator {
	private YZG_KVStorage m;
	private int i;

	static YZG_HashMapIterator internalCreate(YZG_KVStorage kv) {
		let ret = new();
		ret.m = kv;
		ret.i = 0;
		return ret;
	}

	Object, Object next() {
		while (self.i < m.keys.size()) {
			let k = m.keys[self.i];
			let v = m.values[self.i];
			self.i += 1;
			if (k != self.m.empty && k != self.m.tombstone) {
				return k, v;
			}
		}
		return self.m.unoccupied, NULL;
	}
}

class YZG_HashMap {
	private YZG_KVStorage kv;
	private YZG_Hasher hasher;

	static YZG_HashMap create(YZG_Hasher hasher) {
		let ret = new();
		ret.kv = new("YZG_KVStorage");
		ret.kv.keys.resize(8);
		ret.kv.values.resize(8);
		ret.kv.unoccupied = new("YZG_HashUnoccupied");
		ret.kv.empty = new("YZG_HashSentinel");
		ret.kv.tombstone = new("YZG_HashSentinel");
		ret.kv.clear();
		ret.hasher = hasher;
		return ret;
	}

	Object get(Object key) {
		return self.kv.get(key, self.hasher);
	}

	bool containsKey(Object key) {
		return !(self.kv.get(key, self.hasher) is "YZG_HashUnoccupied");
	}

	void resize(uint newSize) {
		self.kv = self.kv.resized(newSize, hasher);
	}

	void insert(Object key, Object value) {
		if (self.kv.loadCount + 1 > uint(self.kv.keys.size() * 0.5)) {
			self.resize(self.kv.keys.size() * 2);
		}
		self.kv.insert(key, value, self.hasher);
	}

	Object remove(Object key) {
		return self.kv.remove(key, self.hasher);
	}

	bool isEmpty() {
		return self.kv.isEmpty();
	}

	void clear() {
		self.kv.clear();
	}

	YZG_HashMapIterator iter() {
		return YZG_HashMapIterator.internalCreate(self.kv);
	}

	String debugRepr() {
		let ret = "";
		for (let i = 0; i < self.kv.keys.size(); i++) {
			ret.appendFormat("%d : ", i);
			let k = self.kv.keys[i];
			if (k == self.kv.empty) {
				ret.appendFormat("EMPTY");
			} else if (k == self.kv.tombstone) {
				ret.appendFormat("TOMBSTONE");
			} else {
				ret.appendFormat("%p -> %p", k, self.kv.values[i]);
			}
			if (i != self.kv.keys.size() - 1) {
				ret.appendFormat("\n");
			}
		}
		return ret;
	}

	double loadFactor() {
		return double(self.kv.loadCount) / double(self.kv.values.size());
	}
	uint bucketCount() {
		return self.kv.values.size();
	}
}

class YZG_HashSetIterator {
	private YZG_HashMapIterator i;

	static YZG_HashSetIterator internalCreate(YZG_HashMapIterator i) {
		let ret = new();
		ret.i = i;
		return ret;
	}

	Object next() {
		return self.i.next();
	}
}

class YZG_HashSet {
	private YZG_HashMap hm;

	static YZG_HashSet create(YZG_Hasher hasher) {
		let ret = new();
		ret.hm = YZG_HashMap.create(hasher);
		return ret;
	}

	bool contains(Object key) {
		return self.hm.containsKey(key);
	}

	void resize(uint newSize) {
		self.hm.resize(newSize);
	}

	void insert(Object key) {
		self.hm.insert(key, NULL);
	}

	Object remove(Object key) {
		return self.hm.remove(key);
	}

	bool isEmpty() {
		return self.hm.isEmpty();
	}

	void clear() {
		self.hm.clear();
	}

	YZG_HashSetIterator iter() {
		return YZG_HashSetIterator.internalCreate(self.hm.iter());
	}

	String debugRepr() {
		return self.hm.debugRepr();
	}
}
